project:
  type: website
  output-dir: docs

website:
  title: "LOGML 2025"
  favicon: favicon.ico
  twitter-card:
    title: "LOGML 2025"
    description: "London Geometry and Machine Learning Summer School, July 7-11 2025"
    image: "https://www.logml.ai/img/logo.png"
    card-style: summary
    site: "@LogmlSchool"
  navbar:
    pinned: true
    logo: "logo.png"
    background: "#73313A"
    foreground: "#FFFFFF"
    width: 3000px
    left:
      - href: people.qmd
        text: People
      - text: Speakers
        href: speaker.qmd
      - text: Projects&Mentors
        href: projects.qmd
      - href: policies.qmd
        text: Policies
      # - href: sponsors.qmd
      #   text: Sponsors
      # - href: program.qmd
      #   text: Schedule
      - href: logml2024/speaker.qmd
        text: "Archives"
 
    right: 
      - icon: youtube
        href: https://www.youtube.com/channel/UC7m0STJK9e4BbD-elwS4bNw
      - icon: twitter
        href: https://twitter.com/LogmlSchool
      - icon: linkedin
        href: https://www.linkedin.com/company/logml/
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/logml.bsky.social

  sidebar:
    - title: "Archives"
      style: "docked"
      background: light
      search: false
      contents:
        - section: "LOGML 2024"
          contents:
            - logml2024/speaker.qmd
            - logml2024/projects.qmd
            - logml2024/sponsors.qmd
            - logml2024/people.qmd
        - section: "LOGML 2022"
          contents:
            - logml2022/speaker.qmd
            - logml2022/projects.qmd
            - logml2022/sponsors.qmd
            - logml2022/people.qmd
        - section: "LOGML 2021"
          contents:
            - logml2021/speaker.qmd
            - logml2021/projects.qmd
            - logml2021/sponsors.qmd
            - logml2021/people.qmd
        
              
  page-footer: 
    left: "Copyright © 2025, LOGML Team" 
    right: 
      - icon: youtube
        href: https://www.youtube.com/channel/UC7m0STJK9e4BbD-elwS4bNw
      - icon: twitter
        href: https://twitter.com/LogmlSchool
      - icon: linkedin
        href: https://www.linkedin.com/company/logml/
      - icon: envelope
        href: mailto:logml.committee@gmail.com
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/logml.bsky.social

format:
  html:
    #mainfont: Proxima Nova
    theme: cosmo
    css: styles.css
    toc: true


resources:
    - CNAME
